'use client'

import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'
import './globals.css'
import Seo from '@/components/seo'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <Seo templateTitle='Home' pathname='/' />
      <head />
      <body>
        <CacheProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  )
}

export default RootLayout
